"""Add group_id to notes table

Revision ID: 18df0bf9fe60
Revises: 534a5ed9e65e
Create Date: 2025-09-13 09:31:22.292045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18df0bf9fe60'
down_revision: Union[str, Sequence[str], None] = '534a5ed9e65e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('group_id', sa.String(), nullable=False))
    op.alter_column('notes', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'notes', 'teacher_insights', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.alter_column('notes', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('notes', 'group_id')
    # ### end Alembic commands ###
